### PR TITLE
Removed unused keyReady & moreKeysWaiting() code

### PR DESCRIPTION
**Pull request by gedankenexperimenter**
This code appears to be vestigial. I may have overlooked something, but when I searched, I couldn't find anything that refers to it.

### CODE REVIEW

**Comment by obra** [comment]
Thanks!

**Comment by gedankenexperimenter** [comment]
`readVersion()` also doesn't seem to be used at all; is it just there for debugging purposes?

**Comment by obra** [comment]
It's still part of the API. (And a part of the API I have a plan to use
soonish ;)

If you're curious about the other side of the conversation, avr_keyscanner
in keyboardio's github.
ᐧ

**Comment by gedankenexperimenter** [comment]
I've looked at avr_keyscanner, but that doesn't tell me what you're planning to use the `read*()` functions for. If you don't mind indulging me, where are these functions going to be called from?

**Comment by obra** [comment]
If a an API implementation. I sometime use them in debugging code. And there’s no reason to remove the implementations of the API because they’re not currently called in the most common consumer code. Your compiler will optimize them out, so there’s no real runtime cost if you don’t use em

**Comment by gedankenexperimenter** [comment]
So, the _raison d'être_ of those functions is debugging, as I had guessed? I thought you were hinting at some other purpose when you said, "…part of the API I have a plan to use soonish".

**Pull request merged**
