### PR TITLE
Reduce the size of the gamma8 array

### PR DESCRIPTION
**Pull request by gedankenexperimenter**
This change reduces the size of the gamma8 LED color level table by a factor of 4 by keeping every fourth entry. 64 values should provide plenty of range for something as coarse as the LEDs on a keyboard. In order to do this, I added a two-bit shift of the color values when they're used as array indexes. I'm not certain that the trade-off is worthwhile, but @algernon thought it would be good to submit this as a PR to have a place to record and discuss the idea.

Note that if we cut it in half again, and use only 5 bits per color, we could store the color info using a bit field and pack all three colors into two bytes instead of three. Again, I'm not certain that the trade-offs will be worthwhile, but I intend to do some testing of the idea, at least in my experimental Kaleidoscope fork.

### CODE REVIEW

**Comment by obra** [comment]
Thanks for the proposal!

I presume the goal of this change is to shave off a few bytes of progmem. What are the actual savings you see from this patch? Have you tried it out to see if there's a visible difference on the Model 01? I'd expect it would be most visible in either the Rainbow or RainbowWave effect if we were going to see something..

**Comment by gedankenexperimenter** [comment]
No, I haven't really tested it out yet. It was an idea I had while trawling through the code. I discussed it with @algernon yesterday, but mainly in theoretical terms. I do intend to try it out, but I'm much more interested in things other than LEDs, so it may be a while before I get around to it. I'm happy to let people who are more motivated try this out ahead of me.

I'm mainly interested in how it might work if we use 5-bit colors instead, but I thought that might be too extreme. When I do test it out, I'll see if I can see the difference between 5, 6, 7, and 8 bits per color, and I'll certainly report my findings here.

**Comment by gedankenexperimenter** [comment]
(The two-bit shift was an arbitrary choice; it could just as easily have been one or three, since I'm not intending this PR to be merged as-is. It's just the best place for recording the discussion.)

**Comment by obra** [comment]
Understood! (FWIW, if we were to switch to 5bpp color, the much bigger wins
would be in changing the wire communication with the attiny)

-j

**Comment by gedankenexperimenter** [comment]
I hadn't even considered the impact of changes to the attiny scanners or the wire protocol; is that a major bottleneck?

**Comment by obra** [comment]
not necessarily. But if we can reduce the amount of data on the bus, we can reduce key scanner latency.

**Comment by gedankenexperimenter** [comment]
I just tried out 5bpp color (removing two more columns than in this PR), and removing the idle optimizations from Kaleidoscope-Hardware-Model01 in order to slow things down. I set the LED mode to the `LEDRainbowEffect` mode, where it slowly dims and brightens as it cycles through the colors. I can just barely see the "stepping" effect as the LEDs jump from one brightness level to another, but I really have to look closely to even get a hint of it; the transitions are generally very smooth to my eye.

**Comment by obra** [comment]
It shouldn't be dimming or brightening at all. It -should- be constant
brightness. (And I believe that changing the gamma table could cause such
an effect.)

On Fri, Mar 23, 2018 at 10:18 AM, Michael Richters <notifications@github.com

**Comment by gedankenexperimenter** [comment]
I definitely perceive dimming and brightening happening, with or without this modification. What do you think would be a good test?

**Comment by obra** [comment]
I've been pondering that. I -think- the best option would probably be to
have half the rows using one version of the mapping code and half the rows
using the other version.  That'd probably give us the easiest basis for
comparison.

**Comment by gedankenexperimenter** [comment]
That would be a good test. Also, much trickier than what I've been doing. I just did a comparison of the `LEDBreatheEffect` (with the default blue color), and I can just barely tell the difference between 5bpp and 8bpp.

**Comment by obra** [comment]
Very smooth LED performance is something I've put a lot of effort into. I
understand the desire to save some space by reducing the size of the lookup
table. Other than saving some bytes, is there a driver for pushing on this?

**Comment by gedankenexperimenter** [comment]
No. But you should take a look at those LED effects now that the average cycle time is much faster. You might want to make some timing adjustments to slow down some of them.

When I say I can just barely tell the difference, that's staring intently at the keys from inches away. From a normal sitting position, I can't tell the difference. And that's with 5bpp; this PR is using 6bpp, and half the table space savings comes with just a drop to 7bpp.

I am going to see if I can do a real side-by-side comparison, but it will be a bit difficult, since the code affected is on the MCU, not the scanners.

**Comment by obra** [comment]
The way I was thinking of doing the testing would be to have to copies of
the tables and two conversion routines and just selecting a different
converter based on the key #.

Some folks are much more sensitive to these kinds of changes than others.
And a dark room can make a big difference too.

**Comment by gedankenexperimenter** [comment]
I set up a basic version, in a dark room, and got it working with one side at 5bpp, and one at 8bpp. My wife and daughters couldn't tell the difference.

That said, I've worked out a better test, where it will randomly choose which side to change, and the number of bits be selectable (all at runtime, using macros). One key will be a macro that reports the side affected via serial port.

This way, the user can convince himself that it works properly by using a very low number (3bpp is obvious), then run the test at 5bpp and see if they can guess correctly.

**Comment by gedankenexperimenter** [comment]
I just had one more idea. If we switch from three bytes to two bytes for RGB values, the extra bit _could_ be used as a global doubler, effectively increasing the value range from 5 bits to 6, at the cost of some math.

**Comment by gedankenexperimenter** [comment]
I went ahead and made a test version of the firmware to demonstrate different numbers of bits per color. This involves two branches, both named `pbt`: [Kaleidoscope-Hardware-Model01](https://github.com/gedankenexperimenter/Kaleidoscope-Hardware-Model01/tree/pbt) & [Model01-Firmware](https://github.com/gedankenexperimenter/Model01-Firmware/tree/pbt). [Don't use this PR, though; use the master version of KeyboardioScanner.]

The test affects one side of the keyboard only (the control side always uses 8 bits/color). The side that's affected is randomly determined when the butterfly key is pressed. The affected side will use a number of bits/color selected by pressing the number keys (from 1-8). The `any` key causes the current values for both sides to be printed via the serial port.

The testers should select an LED mode with slow, gradual changes (Breathe and Rainbow work well), and set the number of bits to a low number (at 3, it becomes obvious), and press the butterfly key a few times to satisfy themselves that the affected side is chosen randomly. Then, the testers should press `5`, and see if that's good enough. Press the butterfly key to randomize the affected keyboard half, and see if you can correctly tell which side is affected.

I've tried it out in a relatively dark room. A 4 bpp, I can fairly easily tell which is which, but it still looks pretty good. At 3 bpp, it's obvious. At 5 bpp, I sometimes guess wrong which side is affected with the "breathe" effect, but if I look very, very carefully for it, I can tell which side is affected when the "rainbow" effect is on.

I will admit that I don't really care much about the LEDs in general, but I'm also very sensitive to detail. I do think this is a worthwhile test, and it doesn't take long to try it out.

**Comment by gedankenexperimenter** [comment]
Also, those two modes are pretty good, but it might be helpful to have a few others to more thoroughly test, with a wider range of brightness values.

**Comment by gedankenexperimenter** [comment]
Another thought just occurred to me on this topic — the whole gamma8 table (and the code for lookups) could be stored on the ATtiny88 keyscanners instead of taking up space on the main MCU, couldn't it?

Changing it now wouldn't make sense, for backwards compatibility reasons, but is there some non-obvious reason it couldn't be done that way?

**Comment by swenson** [comment]
I don't think the ATtiny processors have any extra storage space to spare.

**Comment by obra** [comment]
Right now, the user program on the tiny is about 2.5k. The bootloader is
1k. We have 8k of flash.

However, on the tiny, we're much more focused on the tightest possible
loops so we can keep key matrix scans and LED updates and I2C responses
happening when they should. (That was one of the big wins of decoupling
those functions from the ATMega) All the LED data movement is done with
memcpy. I suspect that doing the gamma table lookups would have a
significant perf penalty.

**Comment by gedankenexperimenter** [comment]
If it changed from 8 to 5 bits per color, and the gamma table lookup happened on the Tinys, that would mean only two bytes transferred per LED, rather than three, so some speed would be gained in the data transfer, but it sounds like that wouldn't come close to making up the difference. Thanks for the explanation.

**Comment by obra** [comment]
I'm sorry I let it sit so long, but I'm going to close this one out.  I don't think the storage space reduction is a good general tradeoff for the reduction in color depth, though I can see why it might be valuable to some users, sometimes.

**Comment by gedankenexperimenter** [comment]
Out of curiosity, did you try my experiment with 5-bit color brightness and determine that you could reliably tell the difference, or did you just decide it wasn't worth the bother?

**Comment by obra** [comment]
In the end, I decided the small reduction in space used wasn't worth the
'perceived' cost / loss of quality / loss of competitive specs of reducing
our color space.
ᐧ

**Pull request closed without merging**
